from os import getenv

STATE = {
	'CANDIDATE': 1,
	'FOLLOWER': 2,
	'LEADER': 3	
}

MIN_TIMEOUT = int(getenv('MIN_TIMEOUT', 50000))
MAX_TIMEOUT =  int(getenv('MAX_TIMEOUT', 100000))

HB_TIME = int(getenv('HB_TIME', 5000))

RESPONSE_CODE_OK = 200
RESPONSE_CODE_REJECT = 500
RESPONSE_CODE_REDIRECT = 300
KEY_NOT_FOUND = -999

CLIENT_SLEEP_TIME = 40
SERVER_SLEEP_TIME = 10/1000
FLUSH_CONFIG_TIME = 10

FLUSH_APPLIED_BATCH_SIZE = 200
FLUSH_APPLIED_TIMEOUT = 10

# RPC timeout in seconds
RPC_TIMEOUT = 100

ELECTION_START_UP_TIME = 60
